Guide update
spring-guides/gs-spring-data-reactive-redis pull request #16
Opened 2024-06-25 13:45 UTC by robertmcnees

This PR updates the guide in a few main areas:

- Spring Boot Docker Compose Support is the preferred method of running an external Redis container.
- Added a new (common) section on building the guide in 4 different ways. A jar file, a Docker container, a native image, and a native image container
- Replace Lombok with Java Record
- Add GitHub Actions CI build

The teaching content remains unchanged.

2024-06-25 13:48 UTC, robertmcnees commented
Adding @mp911de for an optional review. This is similar in scope to other updates to bring Docker Compose support to our guides.

Pinging @chemicL as an optional reviewer as well.

2024-07-05 11:23 UTC, chemicL approved these changes
From a brief look I think the changes are a great refresh.

2024-07-08 14:21 UTC, Buzzardo requested changes

2024-07-08 14:21 UTC, Buzzardo commented on README.adoc
> +== Setting up the Redis server
Capitalize `server`

2024-07-08 14:21 UTC, Buzzardo commented on README.adoc
> +Before you can build a messaging application, you need to set up the server that will
Change `that will` to `to`

2024-07-08 14:21 UTC, Buzzardo commented on README.adoc
> +You will also need to add configuration to an `application.properties` file, as described in greater detail in the <<_preparing_to_build_the_application>> section.
Remove `will`

2024-07-08 14:21 UTC, Buzzardo commented on README.adoc
> +. Click *Dependencies* and select *Spring Reactive Web*, *Spring Data Reactive Redis* and *Docker Compose Support*.
Add a comma before the last `and`

2024-07-08 14:21 UTC, Buzzardo commented on README.adoc
> +To run the code without Spring Boot Docker Compose support, you need a version of Redis running locally to connect to.
Remove `to connect to`

2024-07-08 14:21 UTC, Buzzardo commented on README.adoc
> +If you ran the application using a Docker instruction above, a simple curl command from a terminal or command line will no longer work.
change `above` to `(shown earlier)` - include the parentheses.

2024-07-08 14:21 UTC, Buzzardo commented on README.adoc
> +This is because we are running our containers in a https://docs.docker.com/compose/networking/[Docker network] that is not accessible from the terminal or command line. To run curl commands, we can s
Change `are running` to `run`

2024-07-08 14:21 UTC, Buzzardo commented on README.adoc
> +First, obtain an interactive shell to a new container that is running on the same network as the Redis container and the application:
Change `is running` to `runs`

2024-07-10 10:21 UTC, merged